// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbpf4iJl1gXzCy42DvtB4ULy6p_-i9t0o',
    appId: '1:857344245396:web:32b9187aae2edeac46be81',
    messagingSenderId: '857344245396',
    projectId: 'notificationexample-9694d',
    authDomain: 'notificationexample-9694d.firebaseapp.com',
    storageBucket: 'notificationexample-9694d.appspot.com',
    measurementId: 'G-RS007ND293',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD92PuRPofkV3RFQ_tl3nkrr6SM2-yOuBI',
    appId: '1:857344245396:android:acc429d413c8db2246be81',
    messagingSenderId: '857344245396',
    projectId: 'notificationexample-9694d',
    storageBucket: 'notificationexample-9694d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAw88xdPXbfw9T_xyK9UseVET3zDmVOHM',
    appId: '1:857344245396:ios:2da4093e2382f34446be81',
    messagingSenderId: '857344245396',
    projectId: 'notificationexample-9694d',
    storageBucket: 'notificationexample-9694d.appspot.com',
    iosClientId: '857344245396-3q8dglshvkthkfr46lib4uiqvm03pnqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificationExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAw88xdPXbfw9T_xyK9UseVET3zDmVOHM',
    appId: '1:857344245396:ios:2da4093e2382f34446be81',
    messagingSenderId: '857344245396',
    projectId: 'notificationexample-9694d',
    storageBucket: 'notificationexample-9694d.appspot.com',
    iosClientId: '857344245396-3q8dglshvkthkfr46lib4uiqvm03pnqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificationExample',
  );
}
